"""start table

Revision ID: 7f1274cfbd94
Revises: 
Create Date: 2019-04-10 18:51:03.112864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1274cfbd94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reagent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reagent_name', sa.String(), nullable=False),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('package_unit', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('catalogue_number', sa.String(), nullable=True),
    sa.Column('url_reagent', sa.String(), nullable=True),
    sa.Column('reagent_comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reagent_catalogue_number'), 'reagent', ['catalogue_number'], unique=False)
    op.create_index(op.f('ix_reagent_package'), 'reagent', ['package'], unique=False)
    op.create_index(op.f('ix_reagent_package_unit'), 'reagent', ['package_unit'], unique=False)
    op.create_index(op.f('ix_reagent_reagent_name'), 'reagent', ['reagent_name'], unique=False)
    op.create_index(op.f('ix_reagent_vendor_name'), 'reagent', ['vendor_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=192), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('supervisor', sa.String(length=192), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('laboratory', sa.String(length=192), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_laboratory'), 'user', ['laboratory'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_index(op.f('ix_user_position'), 'user', ['position'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_supervisor'), 'user', ['supervisor'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('item_in_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_published', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reagent_name', sa.String(), nullable=False),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('package_unit', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('catalogue_number', sa.String(), nullable=True),
    sa.Column('url_reagent', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('reagent_aim', sa.String(), nullable=True),
    sa.Column('reagent_comments', sa.String(), nullable=True),
    sa.Column('reagent_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_in_order_catalogue_number'), 'item_in_order', ['catalogue_number'], unique=False)
    op.create_index(op.f('ix_item_in_order_order_published'), 'item_in_order', ['order_published'], unique=False)
    op.create_index(op.f('ix_item_in_order_package'), 'item_in_order', ['package'], unique=False)
    op.create_index(op.f('ix_item_in_order_package_unit'), 'item_in_order', ['package_unit'], unique=False)
    op.create_index(op.f('ix_item_in_order_reagent_aim'), 'item_in_order', ['reagent_aim'], unique=False)
    op.create_index(op.f('ix_item_in_order_reagent_name'), 'item_in_order', ['reagent_name'], unique=False)
    op.create_index(op.f('ix_item_in_order_reagent_status'), 'item_in_order', ['reagent_status'], unique=False)
    op.create_index(op.f('ix_item_in_order_urgency'), 'item_in_order', ['urgency'], unique=False)
    op.create_index(op.f('ix_item_in_order_vendor_name'), 'item_in_order', ['vendor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_in_order_vendor_name'), table_name='item_in_order')
    op.drop_index(op.f('ix_item_in_order_urgency'), table_name='item_in_order')
    op.drop_index(op.f('ix_item_in_order_reagent_status'), table_name='item_in_order')
    op.drop_index(op.f('ix_item_in_order_reagent_name'), table_name='item_in_order')
    op.drop_index(op.f('ix_item_in_order_reagent_aim'), table_name='item_in_order')
    op.drop_index(op.f('ix_item_in_order_package_unit'), table_name='item_in_order')
    op.drop_index(op.f('ix_item_in_order_package'), table_name='item_in_order')
    op.drop_index(op.f('ix_item_in_order_order_published'), table_name='item_in_order')
    op.drop_index(op.f('ix_item_in_order_catalogue_number'), table_name='item_in_order')
    op.drop_table('item_in_order')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_supervisor'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_position'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_laboratory'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_reagent_vendor_name'), table_name='reagent')
    op.drop_index(op.f('ix_reagent_reagent_name'), table_name='reagent')
    op.drop_index(op.f('ix_reagent_package_unit'), table_name='reagent')
    op.drop_index(op.f('ix_reagent_package'), table_name='reagent')
    op.drop_index(op.f('ix_reagent_catalogue_number'), table_name='reagent')
    op.drop_table('reagent')
    # ### end Alembic commands ###
